# Generated by Django 3.2.4 on 2021-09-23 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.IntegerField()),
                ('start_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'تخفیف نقدی',
                'verbose_name_plural': 'تخفیف های نقدی',
            },
        ),
        migrations.CreateModel(
            name='PercentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_discount', models.IntegerField(verbose_name='بیشترین مقدار')),
                ('start_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'تخفیف درصدی',
                'verbose_name_plural': 'تخفیف های درصدی',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_sub_category', models.BooleanField(default=False, verbose_name='زیر دسته')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='book.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('inventory', models.PositiveIntegerField(verbose_name='موجودی')),
                ('available', models.BooleanField(default=True, verbose_name='وجود یا عدم وجود')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='book/', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('cash_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.cashdiscount', verbose_name='تخفیف نقدی')),
                ('category', models.ManyToManyField(blank=True, to='book.Category', verbose_name='دسته بندی')),
                ('percent_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.percentdiscount', verbose_name='تخفیف درصدی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتابها',
            },
        ),
    ]
