# Generated by Django 3.2.4 on 2021-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_sell',
            field=models.IntegerField(default=0),
        ),
    ]
