# Generated by Django 3.2.4 on 2021-10-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='سفارش', max_length=20, verbose_name='وضعیت'),
        ),
    ]
